version: "3.7"
services:
  nginx:
    image: nginx:1.23.0-alpine
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    ports:
      - "5700:5700"
  fhir:
    image: "hapiproject/hapi:v5.6.0"
    ports:
      - "8090:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://fhir-db:5432/hapi_r4"
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY
      hapi.fhir.cors.allowed_origin: "*"
      hapi.fhir.fhir_version: R4
  fhir-db:
    image: postgres:latest
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi_r4

volumes:
  fhir-db-data:
