version: "3.7"
services:
  fhir:
    image: "hapiproject/hapi:v6.1.0"
    ports:
      - "8090:8080"
    environment:
      hapi.fhir.client_id_strategy: ANY
      hapi.fhir.cors.allowed_origin: "*"
      hapi.fhir.fhir_version: R4
      hapi.fhir.allow_cascading_deletes: "true"
      hapi.fhir.reuse_cached_search_results_millis: -1
