ValueSet : GenomicDiseases
Id: GenomicDiseases
Description: "Allowed values for genomic diseases"
* $PANEL_APP#R14 "Acutely unwell children with a likely monogenic disorder"
* $PANEL_APP#R137 "Congenital heart disease - microarray"
* $PANEL_APP#R127 "Long QT syndrome"
* $PANEL_APP#R128 "Brugada syndrome and cardiac sodium channel disease"
* $PANEL_APP#R129 "Catecholaminergic polymorphic VT"
* $PANEL_APP#R130 "Short QT syndrome"
* $PANEL_APP#R131 "Hypertrophic cardiomyopathy"
* $PANEL_APP#R184 "Cystic fibrosis diagnostic test"
* $PANEL_APP#R185 "Cystic fibrosis carrier testing"
* $PANEL_APP#R59 "Early onset or syndromic epilepsy"
* $PANEL_APP#R226 "Inherited parathyroid cancer"
* $PANEL_APP#R207 "Inherited ovarian cancer (without breast cancer)"
* $PANEL_APP#R211 "Inherited polyposis and early onset colorectal cancer - germline testing"
* $PANEL_APP#R215 "CDH1-related cancer syndrome"
* $PANEL_APP#R404 "Testing of unaffected individuals for inherited cancer predisposition syndromes"
* $PANEL_APP#R224 "Inherited renal cancer"
* $PANEL_APP#R364 "DICER1-related cancer predisposition"
* $PANEL_APP#R367 "Inherited pancreatic cancer"
* $PANEL_APP#R193 "Cystic renal disease"
* $PANEL_APP#R173 "Polycystic liver disease"
* $PANEL_APP#R65 "Aminoglycoside exposure posing risk to hearing"
* $PANEL_APP#R298 "Possible structural or mosaic chromosomal abnormality - FISH"
* $PANEL_APP#R297 "Possible structural chromosomal rearrangement - karyotype"
* $PANEL_APP#R265 "Chromosomal mosaicism - karyotype"
* $PANEL_APP#R27 "Congenital malformation and dysmorphism syndromes - microarray and sequencing"
* $PANEL_APP#R28 "Congenital malformation and dysmorphism syndromes - microarray only"
* $PANEL_APP#R29 "Intellectual disability - microarray and sequencing"
* $PANEL_APP#R377 "Intellectual disability - microarray only"
* $PANEL_APP#R343 "Chromosomal mosaicism - microarray"
