name: Deploy to github pages

on:
  # only try to run when test actions have completed on main
  workflow_run:
    workflows: [ "Tests" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test-env
    # only run steps if the workflow didn't fail
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node and enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - run: npm run predeploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # disabling jekyll seems to stop environmental variables from being read by react
          enable_jekyll: true
