name: Deploy to github pages

on:
  # only try to run when test actions have completed on main or deploy_github for testing
#  workflow_run:
#    workflows: [ "Tests" ]
#    branches: [ main, deploy_github ]
#    types:
#      - completed
  push:
    branches:
      - deploy_github

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test-env
    # only run steps if the workflow didn't fail
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node and enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Setup mock git user
        run: |
          git config --global user.email "gmsa@fhir.com"
          git config --global user.name "Unused account"
      - run: npm run deploy
