name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node and enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
      - name: npm test
        run: npm test
