name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_fsh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node and enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: Install sushi
        run: npm install -g fsh-sushi
      - name: Run sushi
        run: sushi SUSHI/GMSA_genomics_reporting
  build_and_test:
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node and enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Run linting
        run: npm run lint
      - name: Setup .env file
        run: cp env/dev.env .env
      - name: Run fake FHIR in docker
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        env:
          REACT_APP_LOINC_USERNAME: ${{secrets.REACT_APP_LOINC_USERNAME}}
          REACT_APP_LOINC_PASSWORD: ${{secrets.REACT_APP_LOINC_PASSWORD}}
        run: npm test
